services:
  wordpress:
    environment:
      - REDIS_HOST=redis
    depends_on:
      - mariadb
      - redis

  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: redis
    networks:
      - inception
    restart: on-failure

  ftp:
    build: ./requirements/bonus/ftp
    image: ftp
    container_name: ftp
    env_file: .env
    secrets:
      - ftp_password
    volumes:
      - wp_data:/var/www/html
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    networks:
      - inception
    restart: on-failure

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - inception
    restart: on-failure

  static-site:
    build: ./requirements/bonus/static-site
    image: static-site
    container_name: static-site
    ports:
      - "8082:8081"
    networks:
      - inception
    restart: on-failure

  netdata:
    build: ./requirements/bonus/netdata
    image: netdata
    container_name: netdata
    ports:
      - "19999:19999"
    networks:
      - inception
    restart: on-failure

secrets:
  ftp_password:
    file: ../secrets/ftp_password.txt
